FROM php:7.2-fpm

# Copy composer.lock and composer.json ./laravelData/composer.lock
COPY ./laravelData/composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    dos2unix

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

# Install composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer


# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www



# RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader && rm -rf /root/.composer
# RUN composer install --prefer-source --no-interaction
RUN composer install  \
    --ignore-platform-reqs \
    --no-ansi \
    --no-autoloader \
    --no-interaction \
    --no-scripts


# Copy existing application directory contents
COPY ./laravelData/ /var/www


COPY ./dockerHub/run.sh /var/www/
RUN dos2unix /var/www/run.sh
RUN /var/www/run.sh


# Copy existing application directory permissions
# COPY --chown=www:www . /var/www
RUN chown -R www:www /var/www


# Change current user to www
USER www


# RUN php artisan key:generate
# RUN php artisan config:clear
# RUN php artisan make:controller MyController
# RUN php artisan migrate
# RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache




# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]