version: '3'
services:


  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tems/php
    container_name: app
    #restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    tty: true
    volumes:
      - ./laravelData/:/var/www
      - ./dockerHub/php/local.ini:/usr/local/etc/php/conf.d/local.ini
     # - ./laravelData/vendor:/var/www/vendor


    #command: bash -c "/root/app_bash.sh"
    #command: "composer install"
    #command: "ls"
    networks:
      - app-network





#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  data-volume:
    # driver: local

